export const customerSaleNote = {
  CREATED: 'CREATED',
  TERMINATED: 'TERMINATED',
  VOIDED: 'VOIDED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  PENDING_DOWN_PAYMENT: 'PENDING DOWN PAYMENT',
  MANUAL: 'MANUAL'
};

export const producerStatus = {
  ACTIVE: 'ACTIVE',
  PENDING_REVIEW: 'PENDING REVIEW',
  STARTED: 'STARTED',
  INACTIVE: 'INACTIVE'
};
